version: "3.11"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - dev-static-data:/vol/web
    command: >
      sh -c "uvicorn main:app --proxy-headers --host 0.0.0.0 --port 80"
    environment:
      - DEBUG=1

volumes:
  dev-static-data:
